# Generated by Django 3.1.2 on 2020-11-24 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cv',
            new_name='Contact',
        ),
    ]
